# Louis' Python Notes

## Libraries to Import

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Basic Variable Types

In [2]:
#Arithmetic
a = 5
b = 3
a+b #addition

8

In [3]:
a-b #subtraction

2

In [4]:
a*b #multiplication

15

In [5]:
a/b #division

1.6666666666666667

In [6]:
a//b #integer division

1

In [7]:
a%b #remainder

2

In [8]:
#round to 2 decimal places
result = a/b
k = 2 
round(result,k)

1.67

In [9]:
age = 22 #how to format certain strings
print(f'Louis is {age} years old.')

Louis is 22 years old.


In [10]:
name = 'Louis Sungwoo Cho' #strings
school = 'UIUC'
print(name,school) #comma adds a space between two variables when printing in python

Louis Sungwoo Cho UIUC


# Python Functions & Basic Data Structures

In [11]:
louis_list = [] #this is a list

In [12]:
louis_list.append(0) #append 0 to list
louis_list

[0]

In [13]:
for i in range(3):
    louis_list.append(i)
louis_list

[0, 0, 1, 2]

In [14]:
unsorted = [5,1,7,6,2,4,5] #Python sort function
sorted_ = sorted(unsorted)
sorted_

[1, 2, 4, 5, 5, 6, 7]

In [15]:
#How to define a function in Python
#Always start off by writing 'def'
#def() inside the parenthesis, you will put the variables

#Compute Fibonnacci Number f[i] = f[i-1] + f[i-2]

def fib(n):
    f = [0 for i in range(n)] #initializes 0 for n times for an array
    f[0] = 0 #sets the first element to 0
    f[1] = 1 #sets the second element to 1
    
    for i in range(2,n): #for i in range 2 to the index of the last element n-1
        f[i] = f[i-1]+f[i-2] #assign the variable
        
    return f[n-1] #return the last element of the variable

In [16]:
answer = fib(8)
answer

13

In [17]:
#You can return multiple variables using Python functions
def fib(n):
    f = [0 for i in range(n)] #initializes 0 for n times
    f[0] = 0 #sets the first element to 0
    f[1] = 1 #sets the second element to 1
    
    for i in range(2,n): #for i in range 2 to the index of the last element n-1
        f[i] = f[i-1]+f[i-2] #assign the variable
        
    return f,f[n-1] #return the last element of the variable

In [18]:
n = 8
dp,answer = fib(n)
print(f'Fibonacci Dynamic Programming Array:{dp}')
print(f'Answer of F(n) when n = 8 is {answer}')

Fibonacci Dynamic Programming Array:[0, 1, 1, 2, 3, 5, 8, 13]
Answer of F(n) when n = 8 is 13


In [19]:
#We can work with 2-Dimensional Arrays
#We will be creating a 3x2 matrix populating each element with 0.
rows = 3
cols = 2
matrix = [[0 for j in range(cols)]for i in range(rows)]
matrix

[[0, 0], [0, 0], [0, 0]]

In [20]:
#How to traverse 2D arrays in Python
#Guess what this function is trying to do
for i in range(rows): #for each row
    for j in range(cols): #we will be traversing each columns
        matrix[i][j] = i+j
matrix

[[0, 1], [1, 2], [2, 3]]

In [46]:
#Tuples:
a = (1,2)
b = (3,4)
# a.append(3) Note this will not work because tuples are immutable
a[0]

1

In [38]:
# Dictionary 
df = {
    'Student':['Louis','Anish','Alex','Jay','Ethan','Christian','Javi','Hugo','Yug'],
    'Major':['CEE','CS','CS','CompE','CEE','AE','EE','ME','CS'],
    'Minor':['CS','NA','Math','Phys','CS','CS','CS','CS','EE']
}

In [39]:
df

{'Student': ['Louis',
  'Anish',
  'Alex',
  'Jay',
  'Ethan',
  'Christian',
  'Javi',
  'Hugo',
  'Yug'],
 'Major': ['CEE', 'CS', 'CS', 'CompE', 'CEE', 'AE', 'EE', 'ME', 'CS'],
 'Minor': ['CS', 'NA', 'Math', 'Phys', 'CS', 'CS', 'CS', 'CS', 'EE']}

In [40]:
# If we want to convert our dictionary to dataframe, we need to call Pandas 
import pandas as pd 

data = pd.DataFrame(df)
first = 10 #how many first rows we want to see
data.head(first)

Student  Major Minor
0      Louis    CEE    CS
1      Anish     CS    NA
2       Alex     CS  Math
3        Jay  CompE  Phys
4      Ethan    CEE    CS
5  Christian     AE    CS
6       Javi     EE    CS
7       Hugo     ME    CS
8        Yug     CS    EE

In [41]:
# Let's convert this into csv file!
data.to_csv('students.csv')

In [42]:
# Let's read the csv file!
input_data = pd.read_csv('students.csv', index_col=[0])
input_data

Student  Major Minor
0      Louis    CEE    CS
1      Anish     CS   NaN
2       Alex     CS  Math
3        Jay  CompE  Phys
4      Ethan    CEE    CS
5  Christian     AE    CS
6       Javi     EE    CS
7       Hugo     ME    CS
8        Yug     CS    EE

# Calculus

### Displacement $x(t)$ 

$$x(t) = v_it+\frac{1}{2}at^2$$

### Compute Velocity $v(t)$

$$ v(t) = \frac{dx}{dt}$$

### Compute Acceleration a(t)

$$ a(t) = \frac{dv}{dt} $$

In [47]:
from sympy import * # I love sympy library :) for calculus!
t = symbols('t')
t

t

## Derivatives

In [67]:
#Compute Displacement
vi = 5 #m/s
a = 10 #m/s^2
x = vi*t+0.5*a*t**2
x

5.0*t**2 + 5*t

In [68]:
#Compute Velocity
v = diff(x,t)
v

10.0*t + 5

In [69]:
#Compute Acceleration
a = diff(v,t)
a

10.0000000000000

## Compute $x(t)$ , $v(t)$ and $a(t)$ respectively when t = 3 seconds.

In [70]:
#we are going to compute x(t) when t = 3
x_ans = lambdify(t,x)
ti = 3
x_ans(ti)

60.0

In [71]:
v_ans = lambdify(t,v)
v_ans(ti)

35.0

In [72]:
a_ans = lambdify(t,a)
a_ans(ti)

10.0

# Partial Differentiation

$ f(x,y) = x^2 + y^2 $

$\frac{\partial f}{\partial x} = 2x$

$\frac{\partial f}{\partial y} = 2y$

In [73]:
x,y = symbols('x,y')
f = x**2 + y**2
part_x = diff(f,x)
part_x

2*x

In [74]:
part_y = diff(f,y)
part_y

2*y

# Single Integration

$$\ \int_{a}^{b} x^2 dx \$$

$$\Delta{x} = \int_{t_i}^{t_f} (v_i+ at)dt$$

**Compute the change in displacement when $t_i = 0$ and $t_f = 5$ with $v_i$ = 5 m/s and $a$ = 2 m/s^2**

In [75]:
#Initialize all the variables
vi = 5 #m/s
a = 2 #m/s^2
ti = 0 #seconds
tf = 5 #seconds
t = symbols('t')

In [76]:
vf = vi+a*t
vf

2*t + 5

In [77]:
delta_x = integrate(vf,t)
delta_x

t**2 + 5*t

In [78]:
vf_result = lambdify(t,vf)
delta_x = integrate(vf,(t,ti,tf))
delta_x

50

In [79]:
#what if initial condition of x(0) = 10 m?
x0 = 10
xf = x0 + delta_x
xf

60

# Double Integration 

$$\ \int_{c}^{d} \int_{a}^{b} x^2+y^2 dxdy \$$

$$\ \int_{1}^{3} \int_{2}^{5} x^2+y^2 dxdy \$$

In [80]:
a = 2
b = 5
c = 1 
d = 3
x,y = symbols('x,y')
x,y

(x, y)

In [81]:
f = x**2+y**2
f

x**2 + y**2

In [82]:
delta_x = integrate(f,(x,a,b))
delta_x

3*y**2 + 39

In [83]:
delta_y = integrate(delta_x,(y,c,d))
delta_y

104

# Linear Algebra

In [91]:
# We will be using A LOT of numpy libraries
import numpy as np #Basically for any mathematical calculations
import numpy.linalg as la #You need this for Linear Algebra

$A = 
\begin{bmatrix}
1 & 2  \\
1 & 0 \\
\end{bmatrix}
$

$b = 
\begin{bmatrix}
3  \\
5 \\
\end{bmatrix}
$

$ Ax = b $

In [92]:
A = np.array([[1,2],[1,0]])
b = np.array([3,5])

sol = la.solve(A,b)
sol

array([ 5., -1.])

\begin{align*}
2x + 3y + z &= 10 \\
4x - y + z &= 2 \\ 
3x + y - z &= 3
\end{align*}

In [93]:
#First we need to convert x,y,z into symbols
x,y,z = symbols('x,y,z')
variables = [x,y,z]
variables

[x, y, z]

### Hint:

$A = 
\begin{bmatrix}
2 & 3 & 1  \\
4 & -1 & 1 \\
3 & 1 & -1
\end{bmatrix}
$

$b = 
\begin{bmatrix}
10 \\
2 \\
3 
\end{bmatrix}
$


$ Ax = b $

In [94]:
#Second we need to bring everything to the left and setup 3 equations
b1 = 10
b2 = 2 
b3 = 3

#Combine the equations
eq1 = 2*x + 3*y + z - b1
eq2 = 4*x-y+z - b2 
eq3 = 3*x+y-z -b3
equations = [eq1,eq2,eq3]
equations

[2*x + 3*y + z - 10, 4*x - y + z - 2, 3*x + y - z - 3]

In [100]:
#Call the solver
solutions = solve(equations,variables) #Be careful we are using Sympy solver NOT Numpy because we are dealing with a system of linear equations

In [101]:
# Check the solutions
print(f'X-value: {solutions[x]}')
print(f'y-value: {solutions[y]}')
print(f'z-value: {solutions[z]}')

X-value: 5/7
y-value: 33/14
z-value: 3/2


In [102]:
# Convert the solutions to floating point numbers
print(f'X-value: {float(solutions[x])}')
print(f'y-value: {float(solutions[y])}')
print(f'z-value: {float(solutions[z])}')

X-value: 0.7142857142857143
y-value: 2.357142857142857
z-value: 1.5


## Eigenvalues & Eigenvectors

In [113]:
A = np.array([[1,2],[1,0]])
A

array([[1, 2],
       [1, 0]])

In [114]:
eigenvalues = la.eig(A)
eigenvalues #The first array is for eigenvalues, the second one contains the eigenvectors

(array([ 2., -1.]),
 array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

In [115]:
print(f'Eigenvalues are: {eigenvalues[0]}')

Eigenvalues are: [ 2. -1.]


In [116]:
print(f'Eigenvectors are: {eigenvalues[1]}')

Eigenvectors are: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


# Summation

# $ \sum_{i=0}^{5}i^2 $

In [ ]:
total = 0
n = 5
for i in range(n+1):
    total += i**2
print(total)

# Product

# $ \Pi_{i=1}^{5}i^2 $

In [ ]:
total = 1
for i in range(1,n+1):
    total *= i**2
print(total)

# Probability and Statistics

## [Ethanweed Probability and Statisics Tutorial](https://ethanweed.github.io/pythonbook/04.02-probability.html)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.DataFrame(
    {'probabilities': [.5, .3, .1, .1],
     'eventNames': ["Cars", "Buses", "Subways", "Taxis"],
    }) 

fig = sns.barplot(x='eventNames', y='probabilities', data=df)

### Binomial Distribution

In [ ]:
x = np.random.binomial(n=20, p=1/6, size=1000)

# See what happens if you increase the number of times the experiment is run
#x = np.random.binomial(n=20, p=1/6, size=10000000)
skulls = sns.histplot(x, bins=20,binwidth=1)
skulls.set(xlim=(0,20))
plt.xticks(np.arange(min(x), 20, 1.0))